version: '3'
services:
  code-server:
    build:
      #context: .
      dockerfile: webide-Dockerfile.custom
    container_name: code-server
    environment:
      - PUID=1000  # User ID
      - PGID=1000  # Group ID
      - TZ=Etc/UTC
      - PASSWORD=${CODE_SERVER_PASSWORD:-password}  # A more secure password than the default
      - SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD:-password}  # Use environment variable with fallback
    volumes:
      - ./code-server-data/config:/config
      - ..:/workspace  # Map parent directory as workspace
    ports:
      - 8443:8443
    restart: unless-stopped
